### ISSUE TITLE
App crash due to format exception

### ISSUE THREAD

**Issue by Shahul3D** [noveogroup/android-logger#41]
Log.a("jsonResponse" + jsonResponse);

This caused the below crash:
java.util.MissingFormatArgumentException: Format specifier: 3a
       at java.util.Formatter.getArgument(Formatter.java:1111)
       at java.util.Formatter.doFormat(Formatter.java:1076)
       at java.util.Formatter.format(Formatter.java:1042)
       at java.util.Formatter.format(Formatter.java:1011)
       at java.lang.String.format(String.java:1803)
       at java.lang.String.format(String.java:1777)
       at com.noveogroup.android.log.PatternHandler.print(PatternHandler.java:355)
       at com.noveogroup.android.log.SimpleLogger.print(SimpleLogger.java:63)
       at com.noveogroup.android.log.AbstractLogger.a(AbstractLogger.java:167)
       at com.noveogroup.android.log.Log.a(Log.java:313)
       at com.myapp.APIController$13.onResponse(ChatController.java:696)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:170)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Is this a known bug? I'm running latest version.

**Comment by igelgrun** [comment]
Fixed in 1.3.6.

Thank you for issue reporting.
